---
- name: Deb13 - установка утилит для deb сборок
  hosts: all
  #hosts: localhost
  #connection: local
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Check /etc/resolv.conf
      ansible.builtin.slurp:
        src: /etc/resolv.conf
      register: resolv_conf
      changed_when: false     # пометить задачу как не изменяющую состояние системы

    - name: DBUG /etc/resolv.conf
      debug:
        msg: "Содержимое /etc/resolv.conf:\n{{ resolv_conf.content | b64decode }}"

    - name: Update apt cache
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: установка стандартных утилит
      apt:
        name: "{{ item }}"
        state: present
      loop: 
          - sudo
          - axel
          - aria2
          - rsync
          - iptables
          - netfilter-persistent
          - sngrep
          - tmux
          - nmap
          - bind9-dnsutils
          - traceroute
          - highlight
          - ccze
          - inxi
          - sysstat
          - strace
          - htop
          - btop
          - atop
          - ncdu
          - tree
          - jq
          - yq
          - dnsutils
          - gnupg2
          - rsyslog
          - smartmontools
          - nvme-cli
          - hdparm
          - sysbench
      ignore_errors: yes

    - name: установка утилит для deb сборок
      apt:
        name: "{{ item }}"
        state: present
      loop: 
          - build-essential
          - devscripts
          - debhelper
          - dh-make
          - dh-sequence-systemd
          - fakeroot
          - lintian
          - pbuilder
          - curl
          - wget
      ignore_errors: yes

    - name: установка утилит для python сборок
      apt:
        name: "{{ item }}"
        state: present
      loop: 
          - python3-all
          - python3-setuptools
          - python3-pip
          - python3-wheel
          - dh-python
          - python3-dev
          - python3-venv
      ignore_errors: yes

    - name: установка утилит для node.js сборок
      apt:
        name: "{{ item }}"
        state: present
      loop: 
          - nodejs
          - npm
      ignore_errors: yes

#    - name: запуск службы rsyslog
#      systemd:
#        name: rsyslog
#        enabled: yes
#        state: started


    - name: Инфо!
      debug:
        msg: "Утилиты настроены."


# ansible-playbook -i "localhost," -c local deb_builds-prepare.yml

